# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_pgdraw <- function(b, c) {
    .Call(`_pgdraw_rcpp_pgdraw`, b, c)
}

